version: '3'

services: 
  web:
    image: nginx
    volumes:
      - ./misc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports: 
      - '8080:80'
    depends_on: 
      - app

  app:
    build: ./services/app
    volumes:
      - ./services/app/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - '3306:3306'
    volumes:
      - ./services/db/data:/var/lib/mysql
      - ./services/db/my.cnf:/etc/mysql/conf.d/my.cnf
